### ISSUE TITLE
An awesome project, yet very disappointed.

### ISSUE THREAD

**Issue by LoganGar** [Pyragon/cryogen-website#1]
Hello,
I love that you're writing websites with Spark, I'm Logan from Rune-Server; and I very often search Github for worthy projects to contribute to. 
I to, love the "Java as a Website backend" idealism. 

This is a great starting point, / learning point for many. 

The problem in which I am disappointed with is that you left out the key files needed to start this up and for others to actively contribute to your open source project. 

A few file[s] I would need to help out in any way would be:

* Any template files that are missing because they have your private information in them (database info etc)
* A blank copy of the SQL tables would be nice, as I'd rather not have to rewrite the SQL records. 
* Any missing documentation on how to contribute / what needs to be done etc.

Yes, I as well have had problems with leechers.. but their are solutions;
Add a license for your code in the repository, and / or force users to contribute any code they add themselves if they do plan on using this as a basis for their website. 
There's many more options to battle the "download and host" kind.. but that shouldn't shun others who would like to contribute code to your project.

Just a few thoughts of mine,
All the best; Logan G.

https://www.rune-server.ee/members/logan/

Skype: LoganGar

E-mail: Logan.Gar@outlook.com

**Comment by Pyragon** [comment]
9cc2f8b5b45f5dd01878b434aab02e9db6975830

Adds a SQL database skeleton, as well as a template properties file.

Right now I'm not intending people to contribute, that's why I haven't advertised it anywhere.
Once it's more complete, I will make some sort of a TODO list.

Leaving these files out was not really intentional, wasn't meant to reduce leechers.

**Comment by Pyragon** [comment]
Also [here](https://discord.gg/uHNc7) is the link to the discord I have for Cryogen at the moment. I don't really use Skype/email that often nor do I go on R-S often anymore.
